### ISSUE TITLE
Broken shield link in readme.

### ISSUE THREAD

**Issue by FrostyTheSouthernSnowman** [databricks/diviner#11]
### Willingness to contribute
The Diviner Community encourages documentation fix contributions. Would you or another member of your organization be willing to contribute a fix for this documentation issue to the Diviner code base?

- [ ] Yes. I can contribute a documentation fix independently.
- [x] Yes. I would be willing to contribute a document fix with guidance from the Diviner community.
- [ ] No. I cannot contribute a documentation fix at this time.

### URL(s) with the issue:

README.rst in the root directory

### Description of proposal (what needs changing):
One of the shields in the readme is broken. The link that the shield is being loaded from does not exist. If someone explained which shield https://img.shields.io/badge/pypi/v/diviner.svg was supposed to load, I would be happy to replace the shield URL with the correct one. I suspect you meant ![PyPI - Downloads](https://img.shields.io/pypi/dw/diviner)

**Comment by BenWilson2** [comment]
Hi @FrostyTheSouthernSnowman thanks for the reporting. The correct badge is in https://github.com/databricks/diviner/pull/9 (check that branch's README). We should have it merged in the next few days!

**Comment by FrostyTheSouthernSnowman** [comment]
Ok. Thank you.

**Comment by BenWilson2** [comment]
Merged now :)

**Comment by FrostyTheSouthernSnowman** [comment]
Great!
